---
{{- if ne .Values.clusterKind "onprem" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
spec:
  ingress:
    - from:
      - podSelector:
          matchExpressions:
            - {key: app.kubernetes.io/name, operator: In, values: [alertmanager]}
            - {key: alertmanager, operator: In, values: [monitoring-nais-alertmanager,monitoring-tenant-alertmanager]}
  policyTypes:
    - Ingress
  podSelector:
    matchLabels: {{ include "smsmanager.selectorLabels" . | nindent 6 }}
---
apiVersion: networking.gke.io/v1alpha3
kind: FQDNNetworkPolicy
metadata:
  name: {{ .Release.Name}}-fqdn
spec:
  egress:
  - ports:
    - port: 8080
      protocol: TCP
    to:
    - fqdns:
      - sysmanp.adeo.no
  podSelector:
    matchLabels: {{ include "smsmanager.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
{{- end }}
