image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images/smsmanager
  tag: "master"
  pullPolicy: IfNotPresent
  pullSecret: "gpr-credentials"

smsEndpoint: ""
smsUsername: ""
smsPassword: ""

clusterKind: "" # mapped by fasit

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
