---
{{- if ne .Values.clusterKind "onprem" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
spec:
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: alertmanager
  policyTypes:
    - Ingress
  podSelector:
    matchLabels: {{ include "smsmanager.selectorLabels" . | nindent 6 }}
---
apiVersion: networking.gke.io/v1alpha3
kind: FQDNNetworkPolicy
metadata:
  name: {{ .Release.Name}}-fqdn
spec:
  egress:
  - ports:
    - port: {{ .Values.smsPort }}
      protocol: TCP
    to:
    - fqdns:
      - {{ .Values.smsHost }}
  podSelector:
    matchLabels: {{ include "smsmanager.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
{{- end }}
