environmentKinds:
  - onprem
  - tenant
  - legacy
  - management
values:
  clusterKind:
    computed:
      template: '"{{ .Kind }}"'
  image.tag:
    displayName: Image tag
    config:
      type: string
  smsEndpoint:
    displayName: SMS-service endpoint (with username and password)
    required: true
    config:
      type: string
      secret: true
  smsHost:
    displayName: SMS-service hostname
    required: true
    config:
      type: string
  smsPort:
    displayName: SMS-service port for host
    required: true
    config:
      type: string
