environmentKinds:
  - onprem
  - tenant
  - legacy
  - management
values:
  naisVakt.smsNumber:
    displayName: SMS number for nais alerts
    config:
      type: string
  naisVakt.pingAlertsOnly:
    displayName: SMS only on alerts tagged nais-vakt
    description: "Disable to get SMS on all critical alerts"
    config:
      type: bool
  clusterKind:
    computed:
      template: '"{{ .Kind }}"'
  image.tag:
    displayName: Image tag
    config:
      type: string
  smsPassword:
    displayName: SMS-service password
    required: true
    config:
      type: string
      secret: true
  smsUsername:
    displayName: SMS-service username
    required: true
    config:
      type: string
  smsHost:
    displayName: SMS-service domain
    config:
      type: string
  platformPartnerId:
    displayName: LinkMobility partner ID
    required: true
    config:
      type: string
