environmentKinds:
  - onprem
  - tenant
  - legacy
  - management
values:
  naisVakt.smsNumber:
    displayName: SMS number for nais-vakt alerts
    config:
      type: string
  clusterKind:
    computed:
      template: '"{{ .Kind }}"'
  image.tag:
    displayName: Image tag
    config:
      type: string
  smsPassword:
    displayName: SMS-service password
    required: true
    config:
      type: string
      secret: true
  smsUsername:
    displayName: SMS-service username
    required: true
    config:
      type: string
  smsEndpoint:
    displayName: SMS-service endpoint
    config:
      type: string
  smsHost:
    displayName: SMS-service hostname
    config:
      type: string
  smsPort:
    displayName: SMS-service port for host
    config:
      type: string
