image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images/smsmanager
  tag: "latest"

naisVakt:
  smsNumber: ""
  pingAlertsOnly: true

smsEndpoint: "https://n-eu.linkmobility.io/sms/send"

clusterKind: "" # mapped by fasit

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
