name: Deploy to navikt/nais-yaml
on:
  push:
    branches:
      - master

jobs:
  build-push:
    name: Create and push Docker image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set image tag
        run: echo "IMAGE=docker.pkg.github.com/${GITHUB_REPOSITORY}/smsmanager:$(date "+%Y-%m-%d")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Login to Github Package Registry
        env:
          DOCKER_USERNAME: x-access-token
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin docker.pkg.github.com
      - name: Build image
        run: docker build -t $IMAGE .
      - name: Push image
        run: docker push $IMAGE
      - name: Set IMAGE as output
        id: image
        run: echo ::set-output name=image::${IMAGE}

  deploy:
    name: Deploy to Kubernetes
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkout nais-yaml
        uses: actions/checkout@v2
        with:
          repository: navikt/nais-yaml
          token: ${{ secrets.SRVNAIS_REPO_PUSH_PAT }}
          path: nais-yaml
      - name: Bump version in nais-yaml
        run: |
          export version=${{needs.build-push.outputs.image}}
          cd nais-yaml
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          sed -E -i "s#image: docker.pkg.github.com/nais/smsmanager/smsmanager:.+#image: ${version}#" vars/global.yaml
          git add .
          git --no-pager diff --cached
          git --no-verify commit -a -m "Bump SMSManager to version ${version}"
          git push
